// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABE0j6nw4-D6egtQhOnqjrgOWrQf-gmQE',
    appId: '1:839893684341:web:3915fd4994c67b80aae83c',
    messagingSenderId: '839893684341',
    projectId: 'fintxapp-expensage',
    authDomain: 'fintxapp-expensage.firebaseapp.com',
    storageBucket: 'fintxapp-expensage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9Bsr4Opy4s4rzUmd2jPw2JwkRo-jrpc',
    appId: '1:839893684341:android:80f69f33e73dc8d6aae83c',
    messagingSenderId: '839893684341',
    projectId: 'fintxapp-expensage',
    storageBucket: 'fintxapp-expensage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFWbfpsTdzXjYrpbc49EQO4iTLQKmBXw',
    appId: '1:839893684341:ios:fba436e857c89529aae83c',
    messagingSenderId: '839893684341',
    projectId: 'fintxapp-expensage',
    storageBucket: 'fintxapp-expensage.firebasestorage.app',
    iosBundleId: 'com.example.expensag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFWbfpsTdzXjYrpbc49EQO4iTLQKmBXw',
    appId: '1:839893684341:ios:fba436e857c89529aae83c',
    messagingSenderId: '839893684341',
    projectId: 'fintxapp-expensage',
    storageBucket: 'fintxapp-expensage.firebasestorage.app',
    iosBundleId: 'com.example.expensag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABE0j6nw4-D6egtQhOnqjrgOWrQf-gmQE',
    appId: '1:839893684341:web:1666a29bd3d8ed35aae83c',
    messagingSenderId: '839893684341',
    projectId: 'fintxapp-expensage',
    authDomain: 'fintxapp-expensage.firebaseapp.com',
    storageBucket: 'fintxapp-expensage.firebasestorage.app',
  );
}
